/* MEDICATION RECORD 

for non swift users, this code is doing three separate things 
deifning the shape --> what fields exist 
defining how to create it through init
defining how values get assigned to become stored data --> self.x = x 

the "form template" is the struct, with different fields 
init is where we actually fill out the form
self.name = name is where we saving the form answers 

ex: when we say 

let med = MedicationRecord(
    name: "vitamin d"
    dosage: 1000
    frequency: daily 
)

init assigns defaults UUID and Date() 
and self.name = name and self.dosage = dosage assign respectively 

so med becomes a full object 


*/ 

import Foundation 

//creating the data struct, can be turned into a JSON and back 
//every medication record has the following fields/properties 
struct MedicationRecord: Codable, Identifiable {
    
    //universally unique identifier, every medication gets its unique ID 
    let id: UUID 
    
    var name: String
    var dosage: String
    var frequency: String

    //question mark means optional 
    var purpose: String?

    var notes: String? 
    let createdAt: Date
    var updatedAt: Date

    //we want swift to automatically fill in id and createdAt
    //id exists as a property/field inside the struct AND a param in init 
    //constructor 
    init(

        id: UUID = UUID(),
        //if no id passed in, automatically create a new UUID 

        name: String,

        dosage: String,

        frequency: String,

        purpose: String? = nil,

        createdAt: Date = Date(),
        //if not provided, use current date 

        updatedAt: Date = Date() 
        //default to now 
    ) {
        self.id = id 
        //take the id (passed in out autogenerated) and store in struct

        //copying the incoming values into the struct's fields
        self.name = name
        self.dosage = dosage
        self.frequency = frequency
        self.purpose = purpose
        self.notes = notes
        self.createdAt = createdAt
        self.updatedAt = updatedAt 
    }
}
