/* SCHEDULE 

Read MedicationRecord.swift file for more thorough comments, to understand the details
This follows same format!!

Tracking how and when medication should be taken. 
This is the plan/reminder system attached to the medication. Not the functioning of the reminders but the labels

MedicationRecord has its own UUID 
Schedule has its own unique id --> id, but it ALSO points to medicationId to tell us which medication the schedule belongs to

*/




import Foundation 

structure Schedule: Codable, Identifiable {
    let id: UUID 
    //unique ID for schedule itself
     
    let medicationId: UUID 
    //links the schedule back to specific medication
    //MedicationRecord.id = A123
    //Schedule.medicationId = A123
    //specifies that this schedule belongs to that specific med
    //the schedule's own ID can be 234567 but it belongs to medication A123
    //connected by Schedule.medicationId

    var time: String
    //time does should happen (currently stored as text)

    var recurrence: String
    //daily, weekly, twice daily, etc.

    var reminderEnabled: Bool
    //true == reminders on, false == reminders off

    var reminderLabel: String?
    //optional custom reminder message (emoji or incognito sign for privacy)

    let createdAt: Date 
    //when schedule was created

    var updatedAt: Date 
    //schedule last changed 

    //same as MedicationRecord, this is creating the actual form 
    init(
        id: UUID = UUID(),
        //autogenerated new schedule ID unless explicitly given 

        medicationId: UUID,
        //schedule MUST belong to a medication

        time: String,

        recurrence: String,

        reminderEnabled: Bool = true,
        //default unless otherwise stated -- this is tbd, need to discuss w group 

        reminderLabel: String? = nil,

        createdAt: Date = Date()
        updatedAt: Date = Date() 
    
    ) {
        //assigning values 
        //take the input and store it inside THIS schedule object (the one inside the struct)
        self.id = id 
        self.medicationId = medicationId
        self.time = time
        self.recurrence = recurrence
        self.reminderEnabled = reminderEnabled
        self.reminderLabel = reminderLabel
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}